#springboot日志格式
logging:
  pattern:
    console: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %line %clr(:){faint} %m%n'

# Spring boot application
spring:
  application:
    name: dubbo-account

dubbo:
  scan:
    base-packages: com.liangh.seata.demo.dubbo.order.service
  protocol:
    name: dubbo
    port: 20861
  registry:
    address: zookeeper://localhost:2181

